steps:
  # 构建Docker镜像
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/power-prediction-backend:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/power-prediction-backend:latest',
      '.'
    ]
    dir: 'backend'

  # 推送镜像到Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/power-prediction-backend:$BUILD_ID'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/power-prediction-backend:latest'
    ]

  # 部署到Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'power-prediction-backend',
      '--image', 'gcr.io/$PROJECT_ID/power-prediction-backend:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '2Gi',
      '--cpu', '1',
      '--max-instances', '15',
      '--concurrency', '80',
      '--timeout', '300',
      '--set-env-vars', 'ENVIRONMENT=production,PORT=8080,ALLOWED_HOSTS=*'
    ]

# 镜像配置
images:
  - 'gcr.io/$PROJECT_ID/power-prediction-backend:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/power-prediction-backend:latest'

# 构建选项
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
